### ISSUE TITLE
Undefined function or variable 'endpoints12dentity'.

### ISSUE THREAD

**Issue by soichih** [brainlife/app-streamlineCategorySegmentation#1]
The master branch of this App is failing with the following error message.

```
Undefined function or variable 'endpoints12dentity'.

Error in bsc_streamlineCategoryPriors_v4 (line 146)


Error in bsc_streamlineCategoryPriors_BL (line 38)

MATLAB:UndefinedFunction
```

**Comment by DanNBullock** [comment]
What branch are you on?

**Comment by soichih** [comment]
It's using master
> https://brainlife.io/project/5c33a141836af601cc85858d/process

**Comment by DanNBullock** [comment]
1.1 is the app version and works.

**Comment by soichih** [comment]
Ah OK. The user must have submitted the rule with old version.
